### ISSUE TITLE
怎样改变射击速度?

### ISSUE THREAD

**Issue by minkyoyeah** [CharlesPikachu/Games#10]
(original)
if event.type == pygame.MOUSEBUTTONDOWN:
				my_bullet = myaircraft.shot()
				if my_bullet:
					my_bullets_group.add(my_bullet)
(change)
#if event.type == pygame.MOUSEBUTTONDOWN:
my_bullet = myaircraft.shot()
if my_bullet:
    my_bullets_group.add(my_bullet)

我从鼠标的点击中删除了子弹,从而改变了我的目标。 我想加快我的拍摄速度,但是我该怎么办呢?

I deleted the shot from the click of the mouse and changed it so that I could shoot while I was still. I want to speed up my shooting, but what code should I change?

**Comment by CharlesPikachu** [comment]
如果我没理解错的话，你说的是Game13吧，把utils.py文件里的aircraftSprite类的init_count数值改小一些即可。
`class aircraftSprite(pygame.sprite.Sprite):
	def __init__(self, color, bullet_color, **kwargs):
		......
		# 子弹是否在冷却中
		self.is_cooling = False
		self.init_count = 35  --> the value you should adjust
		self.cooling_count = self.init_count
                ......
		`
If I didn't misunderstand your question, the question is about Game13 ?
You could adjust the value of init_count in the class aircraftSprite which defined in utils.py. The smaller, the faster.
