### ISSUE TITLE
[求助]Game19 运行后没有画面

### ISSUE THREAD

**Issue by OrangeViolin** [CharlesPikachu/Games#12]
初次运行游戏程序。

git clone 文件夹之后，运行 PyGame19。

- macOS 10.14.6
- PyGame 1.9.9
- Python 3.7.3

![image](https://user-images.githubusercontent.com/22850695/64031841-d5ce6500-cb7b-11e9-9230-8ffcf56d909f.png)

可以听到音乐但是无法看到画面，不知道哪里出现问题。

![image](https://user-images.githubusercontent.com/22850695/64026882-322c8700-cb72-11e9-8513-5da76b80217b.png)

**Comment by CharlesPikachu** [comment]
可能是Mac OS Mojave与pygame不兼容导致的问题。
比较方便的解决方案是安装Miniconda创建虚拟环境运行后运行代码。
你可以尝试运行：
`python -m pygame.examples.aliens`
若出现与Game19相同的情况，则很可能就是不兼容导致的问题。

**Comment by OrangeViolin** [comment]
换了环境之后解决啦。

![image](https://user-images.githubusercontent.com/22850695/64558932-a8ea3100-d377-11e9-853f-2f8e74e5a9e2.png)
