### ISSUE TITLE
game too hard 

### ISSUE THREAD

**Issue by joekillia** [CharlesPikachu/Games#16]

**Comment by CharlesPikachu** [comment]
Well, the game is hard maybe since I did not adjust the game parameters carefully.
However, in fact, this repo is mainly for python learning rather than playing games.
If you are interested in one of the games, you could modify the game parameters for better enjoy.

**Comment by x931890193** [comment]
> _No description provided._

害 咋还玩上了呢， 人家是用来学习python的 😂

**Comment by epic2305** [comment]
e

**Comment by 2453821075** [comment]
if game_interface.game_map.isValidPos(*next_pos):
不是很明白这段代码
