### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe5' in file Game23.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by SDRStuff** [CharlesPikachu/Games#28]
When I try to open the.py file this error occurs
SyntaxError: Non-ASCII character '\xe5' in file Game23.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details 
Thanks!

**Comment by CharlesPikachu** [comment]
Are you using py2? If yes, try to add `# -*- coding: UTF-8 -*-` in the first line and see whether the error still exists.

**Comment by SDRStuff** [comment]
Thanks! that worked
