### ISSUE TITLE
hello, I want to contribute this game.

### ISSUE THREAD

**Issue by minkyoyeah** [CharlesPikachu/Games#4]
Hello? I am first time in git-hub, so if I rude tell me please... Anyway... I interested in game, and python. I want to contribute this project. I can translate annotate  to English,Korean. 
And We can exchange Idea... And I can add more contents to Readme.md.  And I can also use Python.(I am studying now...very diligently)... so can I contribute this project? If you tell me what kind of help do you need, I will help you.

**Comment by Duotun** [comment]
@minkyoyeah , In my mind, maybe you could contact the editor from the reference link to talk about these games.

**Comment by minkyoyeah** [comment]
@Duotun 
The reference link is only connected to game 1, but isn't it created by Charles Pikachu from game2 to game16? Game1 is right to contact the editor from the reference link, but if I want to contribute, can't I contact Charles Pikachu from game2 to game16? Do you also contribute? Try it with me.

**Comment by Duotun** [comment]
It seems you are right about this. Sorry, I don’t intend to contribute this and just try to learn some things from these games. However, I think you may also contribute to this after forking this project and then make something new based on it. By the way, if you are familiar with wechat, I think you may find the author through that wechat link. I also have no successful contact with this author right now.

_Duotun
________________________________

**Comment by minkyoyeah** [comment]
oh... thank you very much~ You're here to learn pygame. I'm learning too. I want to make game13 extremely difficult. Shooting games like that are really fun when it's hard. I also want to make a cheat key. It would be nice if you could join me while I'm working on it. If you have time, please visit my repository. I haven't started yet. haha~ Have a nice day!
