### ISSUE TITLE
a bug with game8

### ISSUE THREAD

**Issue by ietar** [CharlesPikachu/Games#5]
After selling a tower,'money' changed from type int into type float.
And the program runs much more slowly on my old laptop,due to the CPU.
(Another plane game runs normally. )

卖塔以后钱从整型变成浮点型了
程序在我这个老笔记本上跑的很慢，因为CPU的关系.
(另一个自制的打飞机运行得就还可以)

**Comment by CharlesPikachu** [comment]
Ok, thanks for your feedback. The bug is fixed now.
